apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cve-consumer-role
  namespace: cve-consumer
rules:
- apiGroups: [""]
  resources: ["pods", "services", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]