apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cve-consumer-hpa
  namespace: cve-consumer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "cve-consumer.fullname" . }}
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50